import { describe, expect, it } from "vitest";
import { calculateDashboard } from "../lib/finance";
import { commissionAmounts, expenseInputSchema, saleInputSchema } from "../lib/domain";
import type { Expense, Sale } from "../lib/types";

const baseSale = { id:"",submitted_at:"",origin:"website",original_chat_id:null,description:"",approved_at:"",approved_by:"svetlana",sheet_sync_status:"synced",sheet_sync_error:null,notification_status:"not_required",notification_error:null } as const;
const baseExpense = { id:"",submitted_at:"",submitted_by:"kevin",origin:"website",original_chat_id:null,category:"Other",allocated_at:"",allocated_by:"svetlana",sheet_sync_status:"synced",sheet_sync_error:null,notification_status:"not_required",notification_error:null } as const;
function sale(reference:string,submitted_by:Sale["submitted_by"],project:"A"|"B",amount:number,split:[number,number,number],status:"pending"|"approved"="approved"):Sale { const c=status==="approved"?commissionAmounts(amount,split):{pool:0,richard:0,anastasia:0,jeanClaude:0}; return {...baseSale,reference,submitted_by,customer:"x",project,amount_cents:amount*100,proposed_richard:split[0],proposed_anastasia:split[1],proposed_jean_claude:split[2],final_richard:status==="approved"?split[0]:null,final_anastasia:status==="approved"?split[1]:null,final_jean_claude:status==="approved"?split[2]:null,commission_pool_cents:c.pool,commission_richard_cents:c.richard,commission_anastasia_cents:c.anastasia,commission_jean_claude_cents:c.jeanClaude,status}; }
function expense(reference:string,amount:number,proposed:"A"|"B"|"COMPANY",final:"A"|"B"|"COMPANY"|null):Expense { return {...baseExpense,reference,description:"x",amount_cents:amount*100,proposed_allocation:proposed,final_allocation:final,status:final?"allocated":"awaiting_allocation"}; }

describe("assignment business rules",()=>{
  it("rejects invalid splits and non-positive amounts",()=>{ expect(()=>saleInputSchema.parse({reference:"S",customer:"x",project:"A",description:"x",amount:1,proposedRichard:60,proposedAnastasia:30,proposedJeanClaude:20})).toThrow(); expect(()=>expenseInputSchema.parse({reference:"E",description:"x",category:"Other",amount:0,proposedAllocation:"A"})).toThrow(); });
  it("assigns a rounding difference by largest-share tie order",()=>{ const c=commissionAmounts(10.05,[50,50,0]); expect(c.pool).toBe(101); expect(c.richard+c.anastasia+c.jeanClaude).toBe(101); expect(c.richard).toBe(50); expect(c.anastasia).toBe(51); });
  it("matches Test 1 totals",()=>{ const d=calculateDashboard([sale("S01","richard","A",1000,[50,30,20]),sale("S02","anastasia","B",2000,[20,40,40])],[expense("E01",120,"A","A"),expense("E02",80,"B","A"),expense("E03",100,"COMPANY","COMPANY")]); expect(d.projectResult).toEqual({A:70000,B:180000}); expect(d.companyResult).toBe(240000); expect(d.earned).toEqual({richard:9000,anastasia:11000,jeanClaude:10000}); });
  it("matches cumulative Test 2 totals and pending treatment",()=>{ const d=calculateDashboard([sale("S01","richard","A",1000,[50,30,20]),sale("S02","anastasia","B",2000,[20,40,40]),sale("S03","jean_claude","A",1500,[20,30,50]),sale("S04","richard","B",800,[25,25,50]),sale("S05","richard","B",600,[100,0,0],"pending")],[expense("E01",120,"A","A"),expense("E02",80,"B","A"),expense("E03",100,"COMPANY","COMPANY"),expense("E04",250,"B","B"),expense("E05",90,"A","B"),expense("E06",60,"COMPANY","COMPANY"),expense("E07",140,"A",null)]); expect(d.approvedIncome).toEqual({A:250000,B:280000}); expect(d.commissions).toEqual({A:25000,B:28000}); expect(d.allocatedExpenses).toEqual({A:20000,B:34000}); expect(d.projectResult).toEqual({A:205000,B:218000}); expect(d.companyResult).toBe(393000); expect(d.pendingSales).toBe(60000); expect(d.awaitingAllocation).toBe(14000); expect(d.earned).toEqual({richard:14000,anastasia:17500,jeanClaude:21500}); });
});
