import { currentEmployee } from "@/lib/auth";
import { calculateDashboard } from "@/lib/finance";
import { EMPLOYEES, euros } from "@/lib/domain";
import { adminDb } from "@/lib/supabase";
import type { Expense, Sale } from "@/lib/types";
import { selectRole, retryIntegration } from "./actions";
import { ExpenseDecision, ExpenseForm, SaleDecision, SaleForm, TelegramLinkForm } from "./components";

export const dynamic = "force-dynamic";

export default async function Home() {
  const actor = await currentEmployee(); const role = EMPLOYEES[actor].role;
  let sales: Sale[] = [], expenses: Expense[] = [], configurationError = "";
  try {
    const db = adminDb();
    const [s, e] = await Promise.all([db.from("sales").select("*").order("submitted_at", { ascending: false }), db.from("expenses").select("*").order("submitted_at", { ascending: false })]);
    if (s.error) throw s.error; if (e.error) throw e.error; sales = s.data as Sale[]; expenses = e.data as Expense[];
  } catch (error) { configurationError = error instanceof Error ? error.message : "Database unavailable"; }
  const visibleSales = role === "manager" ? sales : sales.filter(s => s.submitted_by === actor);
  const visibleExpenses = role === "manager" ? expenses : expenses.filter(e => e.submitted_by === actor);
  const d = calculateDashboard(sales, expenses);
  const links = [["Telegram bot",process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL],["Google Sheets",process.env.NEXT_PUBLIC_GOOGLE_SHEET_URL],["GitHub",process.env.NEXT_PUBLIC_GITHUB_URL]].filter((x): x is [string,string] => Boolean(x[1]));
  return <main>
    <header><div><h1>Friends Included</h1><p className="muted">Finance system for fictional wedding guests · {process.env.NEXT_PUBLIC_STUDENT_NAME || "Student name pending"}</p></div><form action={selectRole}><label>Demonstration role<select name="role" defaultValue={actor}>{Object.entries(EMPLOYEES).map(([key,e])=><option value={key} key={key}>{e.name}</option>)}</select></label><button>Switch role</button></form></header>
    {configurationError && <section className="card"><h2>Setup required</h2><p className="error">{configurationError}</p><p>Add the environment variables and apply the Supabase schema to connect real data.</p></section>}
    <section className="card"><h2>How to use</h2><p>Choose a demonstration role. Salespeople submit sales, Kevin submits expenses, and Svetlana reviews pending records and sees the company dashboard. Telegram and website entries use the same server-side rules.</p><div className="links">{links.map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer">{name}</a>)}</div></section>
    <section><h2>Transactions</h2><div className="grid">{role === "salesperson" && <div className="card"><h3>Submit a sale</h3><SaleForm/></div>}{role === "expense_reporter" && <div className="card"><h3>Submit an expense</h3><ExpenseForm/></div>}<div className="card"><h3>Your available records</h3><p>{visibleSales.length} sales · {visibleExpenses.length} expenses</p></div></div></section>
    {role === "manager" && <><section><h2>Financial dashboard</h2><div className="metrics">{[["Project A result",d.projectResult.A],["Project B result",d.projectResult.B],["Company result",d.companyResult],["Company overhead",d.companyOverhead],["Awaiting allocation",d.awaitingAllocation],["Pending sales",d.pendingSales]].map(([l,v])=><div className="metric" key={String(l)}><span>{l}</span><strong>{euros(Number(v))}</strong></div>)}</div><div className="grid"><div className="card"><h3>Project A</h3><p>Income {euros(d.approvedIncome.A)} · commissions {euros(d.commissions.A)} · expenses {euros(d.allocatedExpenses.A)}</p></div><div className="card"><h3>Project B</h3><p>Income {euros(d.approvedIncome.B)} · commissions {euros(d.commissions.B)} · expenses {euros(d.allocatedExpenses.B)}</p></div><div className="card"><h3>Commission earned</h3><p>Richard {euros(d.earned.richard)} · Anastasia {euros(d.earned.anastasia)} · Jean-Claude {euros(d.earned.jeanClaude)}</p></div></div></section><section className="card"><h2>Telegram employee setup</h2><p>Only the manager can map a Telegram user and chat ID. Bot users cannot assign themselves.</p><TelegramLinkForm/></section></>}
    <section className="card"><h2>Sales records</h2><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Salesperson</th><th>Customer and project</th><th>Amount</th><th>Original split</th><th>Final split</th><th>Status and delivery</th>{role === "manager"&&<th>Decision</th>}</tr></thead><tbody>{visibleSales.map(s=><tr key={s.id}><td>{s.reference}</td><td>{EMPLOYEES[s.submitted_by].name}</td><td>{s.customer}<br/>Project {s.project}<br/><span className="muted">{s.description}</span></td><td>{euros(s.amount_cents)}</td><td>{s.proposed_richard}/{s.proposed_anastasia}/{s.proposed_jean_claude}</td><td>{s.final_richard == null ? "—" : `${s.final_richard}/${s.final_anastasia}/${s.final_jean_claude}`}</td><td><span className="status">{s.status}</span><br/>Sheet: {s.sheet_sync_status}<br/>Telegram: {s.notification_error || s.notification_status}{role==="manager"&&s.sheet_sync_status==="failed"&&<Retry kind="sale" reference={s.reference} target="sheet"/>}{role==="manager"&&s.notification_status==="failed"&&<Retry kind="sale" reference={s.reference} target="notification"/>}</td>{role==="manager"&&<td>{s.status==="pending"?<SaleDecision reference={s.reference} split={[s.proposed_richard,s.proposed_anastasia,s.proposed_jean_claude]}/>:"Approved"}</td>}</tr>)}</tbody></table></div></section>
    <section className="card"><h2>Expense records</h2><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Reporter</th><th>Description</th><th>Amount</th><th>Proposal</th><th>Final</th><th>Status and delivery</th>{role === "manager"&&<th>Decision</th>}</tr></thead><tbody>{visibleExpenses.map(e=><tr key={e.id}><td>{e.reference}</td><td>{EMPLOYEES[e.submitted_by].name}</td><td>{e.description}<br/><span className="muted">{e.category}</span></td><td>{euros(e.amount_cents)}</td><td>{e.proposed_allocation}</td><td>{e.final_allocation||"—"}</td><td><span className="status">{e.status}</span><br/>Sheet: {e.sheet_sync_status}<br/>Telegram: {e.notification_error||e.notification_status}{role==="manager"&&e.sheet_sync_status==="failed"&&<Retry kind="expense" reference={e.reference} target="sheet"/>}{role==="manager"&&e.notification_status==="failed"&&<Retry kind="expense" reference={e.reference} target="notification"/>}</td>{role==="manager"&&<td>{e.status==="awaiting_allocation"?<ExpenseDecision reference={e.reference} proposed={e.proposed_allocation}/>:"Allocated"}</td>}</tr>)}</tbody></table></div></section>
  </main>;
}

function Retry({kind,reference,target}:{kind:"sale"|"expense";reference:string;target:"sheet"|"notification"}) { return <form action={retryIntegration}><input type="hidden" name="kind" value={kind}/><input type="hidden" name="reference" value={reference}/><input type="hidden" name="target" value={target}/><button>Retry</button></form>; }
